// packages/grid-svelte/src/components/GridLayout.svelte
<script lang="ts">
  import { DragDropProvider } from "@dnd-kit/svelte";
  import type { GridLayoutProps } from "../props.js";
  import { isInProvider, markInProvider } from "../context.js";
  import GridSurface from "./GridSurface.svelte";

  // Drop-in grid: a controlled, react-grid-layout v2-compatible layout backed by
  // dnd-kit. Supplies the dnd-kit <DragDropProvider> for the turnkey case (unless one
  // already exists above — nested grids and <SnapGridGroup> siblings share it, the
  // cross-grid seam). The surface itself lives in a child component so it initializes
  // *inside* the provider (else the manager context isn't resolvable).
  let props: GridLayoutProps = $props();

  const inProvider = isInProvider();
  if (!inProvider) markInProvider();
</script>

{#if inProvider}
  <GridSurface {...props} />
{:else}
  <DragDropProvider>
    <GridSurface {...props} />
  </DragDropProvider>
{/if}

// packages/grid-react/src/GridLayout.tsx
import { DragDropProvider } from "@dnd-kit/react";
import {
  type CSSProperties,
  Children,
  type ReactNode,
  createContext,
  isValidElement,
  useContext,
} from "react";
import { GridItem } from "./GridItem.js";
import { GridPlaceholder } from "./GridPlaceholder.js";
import { useGridContainer } from "./hooks/useGridContainer.js";
import type { UseGridControllerOptions } from "./hooks/useGridController.js";

export interface GridLayoutProps extends UseGridControllerOptions {
  children: ReactNode;
  /** Appended to the default `snapgrid` class on the surface. */
  className?: string;
  /** Merged over (and able to override) the surface's positioning style. */
  style?: CSSProperties;
}

// Marks that a snapgrid-managed <DragDropProvider> already exists above, so a
// nested GridLayout (or sibling sharing one) doesn't mint a second manager.
const InProvider = createContext(false);

/** Strip the namespacing prefix React applies to keys inside `Children.map`. */
function keyToId(key: string): string {
  return key.startsWith(".$") ? key.slice(2) : key;
}

/** The default surface: positioned container + mapped items + placeholder. */
function GridSurface({ className, style, children, ...opts }: GridLayoutProps) {
  const { containerProps, group } = useGridContainer(opts);
  return (
    <div
      {...containerProps}
      className={className ? `snapgrid ${className}` : "snapgrid"}
      style={style ? { ...containerProps.style, ...style } : containerProps.style}
    >
      {Children.map(children, (child) => {
        if (!isValidElement(child) || child.key == null) return child;
        return (
          <GridItem key={child.key} id={keyToId(String(child.key))} group={group}>
            {child}
          </GridItem>
        );
      })}
      <GridPlaceholder group={group} />
    </div>
  );
}

/**
 * Drop-in grid component: a controlled, react-grid-layout v2-compatible layout
 * backed by dnd-kit. A thin shell over {@link useGridContainer} and the headless
 * hooks — children are keyed by their layout item's `i`. For full control over
 * markup/styling, use the hooks directly.
 *
 * Supplies the dnd-kit `DragDropProvider` for the turnkey case so consumers
 * don't manage one. Nest multiple `GridLayout`s and they share one provider
 * (the seam for cross-grid drags); a consumer's own provider is also honored.
 */
export function GridLayout(props: GridLayoutProps): React.JSX.Element {
  const inProvider = useContext(InProvider);
  const surface = <GridSurface {...props} />;
  if (inProvider) return surface;
  return (
    <DragDropProvider>
      <InProvider.Provider value={true}>{surface}</InProvider.Provider>
    </DragDropProvider>
  );
}

/**
 * Share one dnd-kit `DragDropProvider` across several sibling grids so tiles can
 * be dragged between them. (Nested `GridLayout`s already share a provider; this
 * is for siblings.) A thin wrapper over `DragDropProvider` — the cross-grid seam
 * is the shared manager + collision target.
 */
export function SnapGridGroup({ children }: { children: ReactNode }): React.JSX.Element {
  const inProvider = useContext(InProvider);
  if (inProvider) return <>{children}</>;
  return (
    <DragDropProvider>
      <InProvider.Provider value={true}>{children}</InProvider.Provider>
    </DragDropProvider>
  );
}
