// packages/grid-svelte/src/components/SnapGridGroup.svelte
<script lang="ts">
  import { DragDropProvider } from "@dnd-kit/svelte";
  import type { Snippet } from "svelte";
  import { isInProvider, markInProvider } from "../context.js";

  // Share one dnd-kit <DragDropProvider> across several sibling grids so tiles can be
  // dragged between them. (Nested <GridLayout>s already share a provider; this is for
  // siblings.) A thin wrapper — the cross-grid seam is the shared manager + collision
  // target. Honors a consumer's own enclosing provider.
  let { children }: { children: Snippet } = $props();

  const inProvider = isInProvider();
  if (!inProvider) markInProvider();
</script>

{#if inProvider}
  {@render children()}
{:else}
  <DragDropProvider>
    {@render children()}
  </DragDropProvider>
{/if}

// packages/grid-react/src/SnapGridGroup.tsx
import { DragDropProvider } from "@dnd-kit/react";
import { type ReactNode, useRef } from "react";
import { type GridRegistry, SnapGridGroupContext, createGridRegistry } from "./grouping.js";

export interface SnapGridGroupProps {
  children: ReactNode;
}

/**
 * Wrap multiple grids to let tiles be dragged **between** them. Provides one
 * shared dnd-kit `DragDropProvider` and a registry so each grid can tell which
 * grid the pointer is over.
 *
 * Item ids must be unique across all grids in a group (they share one manager).
 */
export function SnapGridGroup({ children }: SnapGridGroupProps): React.JSX.Element {
  const registryRef = useRef<GridRegistry | null>(null);
  if (!registryRef.current) registryRef.current = createGridRegistry();
  return (
    <DragDropProvider>
      <SnapGridGroupContext.Provider value={registryRef.current}>
        {children}
      </SnapGridGroupContext.Provider>
    </DragDropProvider>
  );
}
