// packages/grid-react/src/GridPlaceholder.tsx
import type { CSSProperties } from "react";
import { useGridPlaceholder } from "./hooks/useGridPlaceholder.js";
import { REFLOW_TRANSITION } from "./reflow.js";

export interface GridPlaceholderProps {
  /** The owning grid's id (from its useGridContainer). */
  group: string;
  /** Appended to the default `snapgrid-placeholder` class. */
  className?: string;
  /** Merged over (and able to override) the default look. */
  style?: CSSProperties;
}

const DEFAULT_LOOK: CSSProperties = {
  background: "rgba(99, 102, 241, 0.2)",
  border: "1px dashed rgba(99, 102, 241, 0.6)",
  borderRadius: 4,
  boxSizing: "border-box",
  zIndex: 2,
  transition: REFLOW_TRANSITION,
};

/**
 * Convenience placeholder rendered from {@link useGridPlaceholder}. Renders
 * nothing when no drag is active. For a custom placeholder, call the hook
 * directly and render your own element with the returned `style`.
 */
export function GridPlaceholder({ group, className, style }: GridPlaceholderProps) {
  const placeholder = useGridPlaceholder(group);
  if (!placeholder) return null;
  return (
    <div
      aria-hidden="true"
      className={className ? `snapgrid-placeholder ${className}` : "snapgrid-placeholder"}
      style={{ ...placeholder.style, ...DEFAULT_LOOK, ...style }}
    />
  );
}

// packages/grid-svelte/src/components/GridPlaceholder.svelte
<script lang="ts">
  import { createGridPlaceholder } from "../hooks/createGridPlaceholder.svelte.js";
  import { REFLOW_TRANSITION } from "../reflow.js";

  interface Props {
    /** The owning grid's id (from its createGridContainer). */
    group: string;
    /** Appended to the default `snapgrid-placeholder` class. */
    class?: string;
    /** Merged after (and able to override) the default look. */
    style?: string;
  }

  let { group, class: className, style: styleOverride }: Props = $props();

  // `group` is the stable grid id for this placeholder's lifetime.
  // svelte-ignore state_referenced_locally
  const placeholder = createGridPlaceholder(group);

  const DEFAULT_LOOK = `background: rgba(99, 102, 241, 0.2); border: 1px dashed rgba(99, 102, 241, 0.6); border-radius: 4px; box-sizing: border-box; z-index: 2; transition: ${REFLOW_TRANSITION};`;
</script>

{#if placeholder.current}
  <div
    aria-hidden="true"
    class={className ? `snapgrid-placeholder ${className}` : "snapgrid-placeholder"}
    style="{placeholder.current.style} {DEFAULT_LOOK}{styleOverride ? ` ${styleOverride}` : ''}"
  ></div>
{/if}
