// apps/docs/components/svelte/ComponentLayerGrid.svelte
<script lang="ts">
  import { GridLayout, type Layout, createContainerWidth } from "@snapgridjs/svelte";
  import DemoTile from "./DemoTile.svelte";
  import { BASIC, GRID, STAGE_WIDTH } from "./demo-config";

  // The turnkey shell: <GridLayout> mints its own DragDropProvider and renders the
  // tiles, resize handles, and placeholder — no factories, no dnd-kit wiring. The rest
  // of the gallery is headless; this one demo shows the component layer.
  let layout = $state<Layout>(BASIC.slice(0, 4));
  const width = createContainerWidth({ initialWidth: STAGE_WIDTH });
</script>

<div class="dg-cl" {@attach width.attach}>
  <GridLayout
    {layout}
    width={width.width}
    gridConfig={GRID}
    resizeConfig={{ handles: ["se"] }}
    onLayoutChange={(next) => (layout = next)}
  >
    {#snippet item(it)}
      <DemoTile label={it.i.toUpperCase()} meta={`${it.w}×${it.h}`} />
    {/snippet}
  </GridLayout>
</div>

// apps/docs/components/vue/ComponentLayerGrid.vue
<script setup>
import { GridLayout, useContainerWidth } from "@snapgridjs/vue";
import { shallowRef } from "vue";
import DemoTile from "./DemoTile.vue";
import { BASIC, GRID, STAGE_WIDTH } from "./demo-config";

// The turnkey shell: <GridLayout> mints its own DragDropProvider (and runs the surface in
// a child component, so the composables still see the manager) and renders the tiles,
// resize handles, and placeholder — no composables, no dnd-kit wiring. The rest of the
// gallery is headless; this one demo shows the component layer. Item content comes from
// the `item` scoped slot.
const layout = shallowRef(BASIC.slice(0, 4));
const { width, setRef } = useContainerWidth({ initialWidth: STAGE_WIDTH });

const resizeConfig = { handles: ["se"] };
const onLayoutChange = (next) => {
  layout.value = next;
};
</script>

<template>
  <div class="dg-cl" :ref="setRef">
    <GridLayout
      :layout="layout"
      :width="width"
      :gridConfig="GRID"
      :resizeConfig="resizeConfig"
      :onLayoutChange="onLayoutChange"
    >
      <template #item="{ item }">
        <DemoTile :label="item.i.toUpperCase()" :meta="`${item.w}×${item.h}`" />
      </template>
    </GridLayout>
  </div>
</template>
