// apps/docs/components/svelte/HeadlessGrid.svelte
<script lang="ts">
  import {
    DragDropProvider,
    type Layout,
    type LayoutItem,
    type UseGridControllerOptions,
  } from "@snapgridjs/svelte";
  import type { Snippet } from "svelte";
  import HeadlessGridHost from "./HeadlessGridHost.svelte";

  // The headless wiring every single-grid demo shares: a dnd-kit DragDropProvider
  // wrapping the grid host. The provider is the OUTERMOST element — createGridContainer
  // must run inside it (it registers the grid's controller on the provider's manager),
  // so the host lives in a child component, not in this body. Mirrors React `HeadlessGrid`.
  let {
    layout,
    width,
    onLayoutChange,
    options,
    resizable = false,
    id,
    content,
    tile,
    isCustom,
  }: {
    layout: Layout;
    width: number;
    onLayoutChange: (next: Layout) => void;
    options?: Omit<UseGridControllerOptions, "id" | "layout" | "width" | "onLayoutChange">;
    resizable?: boolean;
    id?: string;
    content?: Snippet<[LayoutItem]>;
    tile?: Snippet<[LayoutItem, string]>;
    isCustom?: (item: LayoutItem) => boolean;
  } = $props();
</script>

<DragDropProvider>
  <HeadlessGridHost
    {layout}
    {width}
    {onLayoutChange}
    {options}
    {resizable}
    {id}
    {content}
    {tile}
    {isCustom}
  />
</DragDropProvider>

// apps/docs/components/vue/HeadlessGrid.vue
<script setup>
import { DragDropProvider } from "@snapgridjs/vue";
import HeadlessGridHost from "./HeadlessGridHost.vue";

// The headless wiring every single-grid demo shares: a dnd-kit DragDropProvider wrapping
// the grid host. The provider is the OUTERMOST element — useGridContainer must run inside
// it (it registers the grid's controller on the provider's manager) AND Vue resolves
// `inject` from the parent chain, so the host lives in a child component, never in this
// one. Mirrors the React/Svelte `HeadlessGrid`.
defineProps({
  layout: Array,
  width: Number,
  onLayoutChange: Function,
  options: Object,
  resizable: { type: Boolean, default: false },
  id: String,
  isCustom: Function,
});
</script>

<template>
  <DragDropProvider>
    <HeadlessGridHost v-bind="$props">
      <!-- Forward only the slots this demo actually supplied: the host falls back to its
           default tile/content when a slot is absent, so an always-present (but empty)
           forwarded slot would blank the tiles. -->
      <template v-if="$slots.tile" #tile="slotProps">
        <slot name="tile" v-bind="slotProps" />
      </template>
      <template v-if="$slots.content" #content="slotProps">
        <slot name="content" v-bind="slotProps" />
      </template>
    </HeadlessGridHost>
  </DragDropProvider>
</template>
