// apps/docs/components/svelte/ResizeGrid.svelte
<script lang="ts">
  import { type Layout, createContainerWidth } from "@snapgridjs/svelte";
  import DemoTile from "./DemoTile.svelte";
  import { GRID, RESIZE, STAGE_WIDTH } from "./demo-config";
  import HeadlessGrid from "./HeadlessGrid.svelte";

  // Per-item resize constraints: drag any corner; minW/maxW/minH/maxH are enforced.
  // The tile labels double as their constraint ("min 2×1", "max 6×3", "free").
  let layout = $state<Layout>(RESIZE);
  const width = createContainerWidth({ initialWidth: STAGE_WIDTH });
</script>

<div {@attach width.attach}>
  <HeadlessGrid
    {layout}
    width={width.width}
    onLayoutChange={(next) => (layout = next)}
    options={{ gridConfig: GRID, resizeConfig: { handles: ["se"] } }}
    resizable
  >
    {#snippet content(it)}
      <DemoTile label={it.i} meta={`${it.w}×${it.h}`} />
    {/snippet}
  </HeadlessGrid>
</div>

// apps/docs/components/vue/ResizeGrid.vue
<script setup>
import { useContainerWidth } from "@snapgridjs/vue";
import { shallowRef } from "vue";
import DemoTile from "./DemoTile.vue";
import { GRID, RESIZE, STAGE_WIDTH } from "./demo-config";
import HeadlessGrid from "./HeadlessGrid.vue";

// Per-item resize constraints: drag any corner; minW/maxW/minH/maxH are enforced.
// The tile labels double as their constraint ("min 2×1", "max 6×3", "free").
const layout = shallowRef(RESIZE);
const { width, setRef } = useContainerWidth({ initialWidth: STAGE_WIDTH });

const options = { gridConfig: GRID, resizeConfig: { handles: ["se"] } };
const onLayoutChange = (next) => {
  layout.value = next;
};
</script>

<template>
  <div :ref="setRef">
    <HeadlessGrid
      :layout="layout"
      :width="width"
      :onLayoutChange="onLayoutChange"
      :options="options"
      resizable
    >
      <template #content="{ item }">
        <DemoTile :label="item.i" :meta="`${item.w}×${item.h}`" />
      </template>
    </HeadlessGrid>
  </div>
</template>
