// apps/docs/components/vue/ArchivePanelTile.vue
<script setup>
import { useGridItem } from "@snapgridjs/vue";
import ArchiveZone from "./ArchiveZone.vue";

// The static grid tile that hosts the (non-grid) Archive drop zone. Mirrors React/Svelte.
const props = defineProps({
  id: String,
  group: String,
  archived: Array,
  onRestore: Function,
});

const { setRef, style } = useGridItem({ id: props.id, group: props.group });
</script>

<template>
  <div :ref="setRef" :style="style" class="dg-cell">
    <ArchiveZone :archived="archived" :onRestore="onRestore" />
  </div>
</template>

// apps/docs/components/svelte/ArchivePanelTile.svelte
<script lang="ts">
  import { createGridItem } from "@snapgridjs/svelte";
  import ArchiveZone from "./ArchiveZone.svelte";

  // The static grid tile that hosts the (non-grid) Archive drop zone. Mirrors React.
  let {
    id,
    group,
    archived,
    onRestore,
  }: { id: string; group: string; archived: string[]; onRestore: (id: string) => void } = $props();

  // svelte-ignore state_referenced_locally
  const tile = createGridItem({ id, group });
</script>

<div {@attach tile.attach} style={tile.style} class="dg-cell">
  <ArchiveZone {archived} {onRestore} />
</div>
