// apps/docs/components/vue/HeadlessGridHost.vue
<script setup>
import { useGridContainer } from "@snapgridjs/vue";
import DemoTile from "./DemoTile.vue";
import GridPlaceholder from "./GridPlaceholder.vue";
import GridTile from "./GridTile.vue";

// The grid host — rendered inside a DragDropProvider (see HeadlessGrid, or a shared
// SnapGridGroup/provider for multi-grid demos) so useGridContainer resolves the right
// manager. Vue resolves `inject` from the PARENT chain, so this must always be a CHILD
// component of the provider, never the one rendering it. Renders the surface, tiles, and
// the placeholder. Mirrors the React/Svelte `HeadlessGridHost` helper: the headless
// wiring every demo shares. The `content` slot draws a tile's inner content (default:
// DemoTile); the `tile` slot (gated by `isCustom`) supplies a full custom positioned tile.
const props = defineProps({
  layout: Array,
  width: Number,
  onLayoutChange: Function,
  // The per-grid config (gridConfig, dragConfig, compactor, dropConfig, accept…), minus
  // the controlled state the host threads itself.
  options: Object,
  resizable: { type: Boolean, default: false },
  id: String,
  isCustom: Function,
});

// The options are a GETTER function, so the controller tracks whichever fields change.
const { setRef, style, group } = useGridContainer(() => ({
  ...(props.id ? { id: props.id } : {}),
  layout: props.layout,
  width: props.width,
  onLayoutChange: props.onLayoutChange,
  ...(props.options ?? {}),
}));

// `isCustom` is a plain predicate prop — kept out of the template so the expression
// compiler never has to deal with an optional call.
const custom = (item) => (props.isCustom ? props.isCustom(item) : false);
</script>

<template>
  <div :ref="setRef" :style="style" class="dg-grid">
    <template v-for="item in layout" :key="item.i">
      <slot v-if="$slots.tile && custom(item)" name="tile" :item="item" :group="group" />
      <GridTile v-else :id="item.i" :group="group" :resizable="resizable">
        <slot v-if="$slots.content" name="content" :item="item" />
        <DemoTile
          v-else
          :label="item.i.toUpperCase()"
          :meta="`${item.w}×${item.h}`"
          :is-static="item.static ?? false"
        />
      </GridTile>
    </template>
    <GridPlaceholder :group="group" />
  </div>
</template>

// apps/docs/components/svelte/HeadlessGridHost.svelte
<script lang="ts">
  import {
    type Layout,
    type LayoutItem,
    type UseGridControllerOptions,
    createGridContainer,
  } from "@snapgridjs/svelte";
  import type { Snippet } from "svelte";
  import DemoTile from "./DemoTile.svelte";
  import GridPlaceholder from "./GridPlaceholder.svelte";
  import GridTile from "./GridTile.svelte";

  // The grid host — rendered inside a DragDropProvider (see HeadlessGrid, or a
  // shared SnapGridGroup/provider for multi-grid demos) so createGridContainer
  // resolves the right manager. Renders the surface, tiles, and the placeholder.
  // Mirrors the React `HeadlessGridHost` helper (demos.tsx): the headless wiring
  // every demo shares. `content` draws a tile's inner content (default: DemoTile);
  // `tile` (gated by `isCustom`) supplies a full custom positioned tile.
  let {
    layout,
    width,
    onLayoutChange,
    options,
    resizable = false,
    id,
    content,
    tile,
    isCustom,
  }: {
    layout: Layout;
    width: number;
    onLayoutChange: (next: Layout) => void;
    // The per-grid config (gridConfig, dragConfig, compactor, dropConfig, accept…),
    // minus the controlled state the host threads itself.
    options?: Omit<UseGridControllerOptions, "id" | "layout" | "width" | "onLayoutChange">;
    resizable?: boolean;
    id?: string;
    content?: Snippet<[LayoutItem]>;
    tile?: Snippet<[LayoutItem, string]>;
    isCustom?: (item: LayoutItem) => boolean;
  } = $props();

  const container = createGridContainer(() => ({
    ...(id ? { id } : {}),
    layout,
    width,
    onLayoutChange,
    ...(options ?? {}),
  }));
</script>

<div {@attach container.attach} style={container.style} class="dg-grid">
  {#each layout as item (item.i)}
    {#if tile && isCustom?.(item)}
      {@render tile(item, container.group)}
    {:else}
      <GridTile id={item.i} group={container.group} {resizable}>
        {#if content}
          {@render content(item)}
        {:else}
          <DemoTile
            label={item.i.toUpperCase()}
            meta={`${item.w}×${item.h}`}
            isStatic={item.static ?? false}
          />
        {/if}
      </GridTile>
    {/if}
  {/each}
  <GridPlaceholder group={container.group} />
</div>
